// Assemble tools/bank/goosequest.json → src/goosequest.js (engine-facing artifact).
// Adds tier metadata; validates the 99-task contract before emitting.
// Usage: node tools/assemble-gq.mjs
import { readFileSync, writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const src = resolve(root, "tools/bank/goosequest.json");

const TIER_NAMES = [
  "รู้จักโปรเจกต์ goose",
  "โครงสร้าง workspace",
  "CI · Docker · supply chain",
  "Design patterns",
  "Resource & output engineering",
  "Security layers",
  "Subprocess & shell engineering",
  "Findings & verdict ของรีวิว",
  "Capstone — สังเคราะห์"
];

const tasks = JSON.parse(readFileSync(src, "utf8"));
if (!Array.isArray(tasks)) { console.error("FAIL: bank is not an array"); process.exit(1); }
if (tasks.length !== 99) { console.error(`FAIL: expected 99 tasks, got ${tasks.length}`); process.exit(1); }

tasks.forEach((t, i) => {
  const n = i + 1;
  const wantId = "GQ-" + String(n).padStart(3, "0");
  if (t.id !== wantId) { console.error(`FAIL: index ${i} has id ${t.id}, expected ${wantId}`); process.exit(1); }
  const wantTier = Math.ceil(n / 11);
  if (t.tier !== wantTier) { console.error(`FAIL: ${t.id} tier ${t.tier} != expected ${wantTier}`); process.exit(1); }
  if (!Array.isArray(t.answers) || !t.answers.length) { console.error(`FAIL: ${t.id} no answers`); process.exit(1); }
  if (!t.title || !t.task || !t.explain) { console.error(`FAIL: ${t.id} missing title/task/explain`); process.exit(1); }
  if (!/🛠/.test(t.explain)) { console.error(`FAIL: ${t.id} explain missing tools section`); process.exit(1); }
});

// answer-variant sanity: after engine normalization, variants must not collapse to duplicates
const norm = (s) => String(s).toLowerCase().replace(/[,]/g, " ").replace(/["'`*]/g, "")
  .replace(/\s+/g, " ").trim().replace(/[.?!]+$/, "");
tasks.forEach((t) => {
  const seen = new Set();
  t.answers.forEach((a) => {
    const k = norm(a);
    if (seen.has(k)) { console.error(`FAIL: ${t.id} duplicate normalized variant "${a}"`); process.exit(1); }
    seen.add(k);
  });
});

const tiers = TIER_NAMES.map((name, i) => ({ id: i + 1, name, count: 11 }));
const payload = {
  repo: "https://github.com/aaif-goose/goose",
  commit: "1e83e89f556fc60fd396df1fd0f2992f8b2f2dc1",
  reviewNote: "อิงจาก code review 2026-09-18 (evidence-first, file:line จริงทุกข้อ)",
  tiers,
  tasks
};
const out = "// AUTO-GENERATED by tools/assemble-gq.mjs — edit tools/bank/goosequest.json instead\n" +
  "window.RQ_GQ = " + JSON.stringify(payload) + ";\n";
writeFileSync(resolve(root, "src/goosequest.js"), out);
console.log(`ASSEMBLE OK → src/goosequest.js (99 tasks, 9 tiers × 11, ${(out.length / 1024).toFixed(1)} KB)`);
