#!/usr/bin/env python3
"""Regenerate src/mascots.js (base64 data URIs) from assets/crab-*-256.jpg sources.
Pipeline: source 1024px JPG (in nexus-agent game/assets) -> tight square crop -> 256px JPEG q80 -> base64.
Usage: python3 tools/make-mascots.py [src_dir]
"""
import base64, os, sys
from PIL import Image

SRC = sys.argv[1] if len(sys.argv) > 1 else '/root/pi-agents/nexus-agent/game/assets'
NAMES = ['hello', 'cheer', 'encourage']

def process(src, out, size=256, q=80):
    im = Image.open(src).convert('RGB')
    w, h = im.size
    px = im.load()
    minx, miny, maxx, maxy = w, h, 0, 0
    for y in range(0, h, 4):
        for x in range(0, w, 4):
            r, g, b = px[x, y]
            if not (abs(r-13) < 14 and abs(g-17) < 14 and abs(b-23) < 14):
                minx = min(minx, x); maxx = max(maxx, x)
                miny = min(miny, y); maxy = max(maxy, y)
    bw, bh = maxx - minx, maxy - miny
    side = int(max(bw, bh) * 1.16)
    cx, cy = (minx + maxx) // 2, (miny + maxy) // 2
    half = side // 2
    left = max(0, min(cx - half, w - side)); top = max(0, min(cy - half, h - side))
    im = im.crop((left, top, left + side, top + side)).resize((size, size), Image.LANCZOS)
    im.save(out, 'JPEG', quality=q, optimize=True)
    return os.path.getsize(out)

js = ['// RustQuest mascot assets — generated by tools/make-mascots.py from assets/*.jpg',
      '// Style A (flat cartoon, default pending user pick — โจทย์เปิด: เปลี่ยนสไตล์ได้ภายหลัง)',
      'window.RQ_MASCOTS = {']
for n in NAMES:
    src = f'{SRC}/rustquest-crab-{n}.jpg'
    dst = f'assets/crab-{n}-256.jpg'
    process(src, dst)
    b64 = base64.b64encode(open(dst, 'rb').read()).decode()
    js.append(f'  {n}: "data:image/jpeg;base64,{b64}",')
js.append('};')
open('src/mascots.js', 'w').write('\n'.join(js) + '\n')
print('OK -> src/mascots.js', os.path.getsize('src/mascots.js') // 1024, 'KB')
